eqty:
  - LYB
  - AXP
  - VZ
  - AVGO
  - BA
  - CAT
  - JPM
  - CVX
  - KO
  - ABBV
  - DIS
  - CPAY
  - EXR
  - XOM
  - PSX
  - GE
  - HPQ
  - HD
  - MPWR
  - IBM
  - JNJ
  - LULU
  - MCD
  - MRK
  - MMM
  - AWK
  - BAC
  - PFE
  - PG
  - T
  - TRV
  - RTX
  - ADI
  - WMT
  - CSCO
  - INTC
  - GM
  - MSFT
  - DG
  - CI
  - KMI
  - C
  - AIG
  - MO
  - HCA
  - IP
  - HPE
  - ABT
  - AFL
  - APD
  - SMCI
  - RCL
  - HES
  - ADM
  - ADP
  - VRSK
  - AZO
  - LIN
  - AVY
  - ENPH
  - MSCI
  - BALL
  - AXON
  - DAY
  - CARR
  - BK
  - OTIS
  - BAX
  - BDX
  - BBY
  - BSX
  - BMY
  - CTRA
  - CPB
  - HLT
  - CCL
  - QRVO
  - BLDR
  - UDR
  - CLX
  - PAYC
  - CMS
  - CL
  - EPAM
  - CMA
  - CAG
  - ABNB
  - ED
  - GLW
  - CMI
  - CZR
  - DHR
  - TGT
  - DE
  - D
  - DOV
  - LNT
  - STLD
  - DUK
  - REG
  - ETN
  - ECL
  - RVTY
  - EMR
  - EOG
  - AON
  - ETR
  - EFX
  - EQT
  - IQV
  - IT
  - FDX
  - FMC
  - BRO
  - F
  - NEE
  - BEN
  - GRMN
  - FCX
  - DXCM
  - GD
  - GIS
  - GPC
  - ATO
  - GWW
  - HAL
  - DOC
  - LHX
  - PODD
  - CTLT
  - FTV
  - HSY
  - SYF
  - HRL
  - AJG
  - MDLZ
  - CNP
  - HUM
  - WTW
  - ITW
  - CDW
  - TT
  - IPG
  - IFF
  - GNRC
  - NXPI
  - K
  - BR
  - KMB
  - KIM
  - ORCL
  - KR
  - LEN
  - LLY
  - BBWI
  - CHTR
  - L
  - LOW
  - HUBB
  - IEX
  - MMC
  - MAS
  - SPGI
  - MDT
  - VTRS
  - CVS
  - DD
  - MU
  - MSI
  - CBOE
  - LH
  - NEM
  - NKE
  - NI
  - NSC
  - PFG
  - ES
  - NOC
  - WFC
  - NUE
  - OXY
  - OMC
  - OKE
  - RJF
  - PCG
  - PH
  - ROL
  - PPL
  - COP
  - PHM
  - PNW
  - PNC
  - PPG
  - PGR
  - PEG
  - RHI
  - COO
  - EIX
  - SLB
  - SCHW
  - SHW
  - WST
  - SJM
  - SNA
  - AME
  - UBER
  - SO
  - TFC
  - LUV
  - WRB
  - SWK
  - PSA
  - ANET
  - SYY
  - CTVA
  - TXN
  - TXT
  - TMO
  - TJX
  - GL
  - JCI
  - ULTA
  - UNP
  - KEYS
  - UNH
  - BX
  - MRO
  - BIO
  - VTR
  - VFC
  - VMC
  - WY
  - WMB
  - CEG
  - WEC
  - ADBE
  - AES
  - EXPD
  - AMGN
  - AAPL
  - ADSK
  - CTAS
  - CMCSA
  - TAP
  - KLAC
  - MAR
  - FI
  - MKC
  - PCAR
  - COST
  - SYK
  - TSN
  - LW
  - AMAT
  - AAL
  - CAH
  - CINF
  - PARA
  - DHI
  - EA
  - FICO
  - FAST
  - MTB
  - XEL
  - FITB
  - GILD
  - HAS
  - HBAN
  - WELL
  - BIIB
  - NTRS
  - PKG
  - PAYX
  - QCOM
  - ROST
  - IDXX
  - SBUX
  - KEY
  - FOXA
  - FOX
  - STT
  - NCLH
  - USB
  - AOS
  - GEN
  - TROW
  - WM
  - STZ
  - XRAY
  - IVZ
  - INTU
  - MS
  - MCHP
  - CB
  - HOLX
  - CFG
  - JBL
  - ORLY
  - ALL
  - EQR
  - BWA
  - KDP
  - HST
  - INCY
  - SPG
  - EMN
  - AVB
  - PRU
  - UPS
  - WBA
  - STE
  - MCK
  - LMT
  - COR
  - COF
  - WAT
  - NDSN
  - DLTR
  - DRI
  - EVRG
  - MTCH
  - DPZ
  - NVR
  - NTAP
  - ODFL
  - DVA
  - HIG
  - IRM
  - EL
  - CDNS
  - TYL
  - UHS
  - SWKS
  - DGX
  - ROK
  - KHC
  - AMT
  - REGN
  - AMZN
  - JKHY
  - RL
  - BXP
  - APH
  - HWM
  - PXD
  - VLO
  - SNPS
  - ETSY
  - CHRW
  - ACN
  - TDG
  - YUM
  - PLD
  - FE
  - VRSN
  - PWR
  - HSIC
  - AEE
  - ANSS
  - FDS
  - NVDA
  - CTSH
  - ISRG
  - TTWO
  - RSG
  - EBAY
  - GS
  - SBAC
  - SRE
  - MCO
  - 'ON'
  - BKNG
  - FFIV
  - AKAM
  - CRL
  - MKTX
  - DVN
  - TECH
  - GOOGL
  - TFX
  - ALLE
  - NFLX
  - WBD
  - A
  - TRMB
  - ELV
  - CME
  - JNPR
  - BLK
  - DTE
  - CE
  - NDAQ
  - PM
  - IR
  - CRM
  - ROP
  - HII
  - MET
  - TPR
  - CSX
  - EW
  - AMP
  - ZBRA
  - ZBH
  - CPT
  - CBRE
  - MA
  - KMX
  - ICE
  - FIS
  - CMG
  - WYNN
  - LYV
  - AIZ
  - NRG
  - MNST
  - RF
  - BKR
  - MOS
  - EXPE
  - CF
  - APA
  - LDOS
  - GOOG
  - FSLR
  - TEL
  - DFS
  - V
  - MAA
  - XYL
  - MPC
  - TSCO
  - AMD
  - RMD
  - MTD
  - VICI
  - CPRT
  - J
  - ALB
  - FTNT
  - MRNA
  - ESS
  - CSGP
  - O
  - WRK
  - WAB
  - POOL
  - WDC
  - PEP
  - FANG
  - PANW
  - NOW
  - CHD
  - FRT
  - MGM
  - AEP
  - INVH
  - PTC
  - JBHT
  - LRCX
  - MHK
  - PNR
  - VRTX
  - AMCR
  - META
  - TMUS
  - URI
  - ARE
  - HON
  - DAL
  - UAL
  - STX
  - NWS
  - CNC
  - MLM
  - TER
  - PYPL
  - TSLA
  - ACGL
  - DOW
  - EG
  - TDY
  - NWSA
  - EXC
  - GPN
  - CCI
  - APTV
  - ALGN
  - ILMN
  - TRGP
  - BG
  - LKQ
  - DECK
  - ZTS
  - EQIX
  - DLR
  - MOH
  - LVS
comdty:
  - GC=F
  - SI=F
  - PL=F
  - HG=F
  - PA=F
  - HO=F
  - CL=F
  - NG=F
  - RB=F
  - ZC=F
  - ZL=F
  - ZS=F
  - HE=F
  - LE=F
  - CC=F
  - KC=F
  - ZO=F
  - ZR=F
  - SB=F
  - CT=F
  - KE=F
  - BZ=F
crypto:
  - BTC-USD
  - ETH-USD
  - BNB-USD
  - SOL-USD
  - XRP-USD
  - DOGE-USD
  - ADA-USD
  - AVAX-USD
#  - SHIB-USD removing SHIB-USD
  - DOT-USD
  - TRX-USD
  - LINK-USD
  - MATIC-USD
  - ICP-USD
  - NEAR-USD
  - LTC-USD
  - DAI-USD
